sudo: required
addons:
  chrome: stable

language: node_js
node_js:
 - 10.12.0
branches:
  only:
    - /.*/
before_script:
 - npm i
 - cd frontend && npm install -g @angular/cli && npm i && mv -f ../canReportError.d.ts node_modules/rxjs/internal/util/canReportError.d.ts && cd ../
script:
 - npm run test
 - cd frontend
 - npm i rxjs
 - ng build --prod
 - ng test
notifications:
  email:
    recipients:
     - arvind.deshraj@gmail.com
     - srijanreddy98@gmail.com
     - rutvikvijjali30@gmail.com
     - yadagallajaswanthkumar98@gmail.com
     - rohan.s16@iiits.in
